name: Build UF2 supermini

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Pull nRF Connect SDK Toolchain v2.6.1 Docker Image
      run: |
        docker pull ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.1

    - name: Initialize and update nRF Connect SDK inside Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.1 \
        west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.6.1
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/nrf ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.1 \
        west update
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/nrf ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.1 \
        west zephyr-export

    - name: Build
      run: |
          # Define the location of your custom boards
          export ZEPHYR_BASE=/workspace/zephyr
          export ZEPHYR_BOARD_ROOT=/workspace

          # Building the supermini_uf2 board
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.1 \
          west build --pristine --board supermini_uf2 -- -DBOARD_ROOT=$ZEPHYR_BOARD_ROOT -DNCS_TOOLCHAIN_VERSION=NONE
    
    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Firmware UF2
        path: build/zephyr/zephyr.uf2
