# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build UF2 supermini

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo pat update && sudo apt install -y --no-install-recommends \
        cmake \
        ninja-build \
        make \
        python-3-pip
        pip3 install --user west

    - name: Initialize nRF Connect SDK repos
      run: |
        west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.6.1
        cd nrf
        west update
        west zephyr-export

        # Install Python dependencies for Zephyr and NCS
        pip3 install --user -r zephyr/scripts/requirements.txt
        pip3 install --user -r nrf/scripts/requirements.txt

    - name: Build
      # Build your program with the given configuration
      run: west build -b supermini_uf2

